import os
import glob
import logging
import httpx
import asyncio

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
ARCHIVE_DIR = os.path.join(BASE_DIR, '..', 'offline_archive')
OUTPUT_FILE = os.path.join(BASE_DIR, '..', 'mega_index.md')

def chunk_text(text, chunk_size=80000):
    """Yield successive n-sized chunks from text."""
    for i in range(0, len(text), chunk_size):
        yield text[i:i + chunk_size]

async def process_chunk(chunk, chunk_index, source_name):
    logger.info(f"Processing chunk {chunk_index} for {source_name}...")
    prompt = (
        "You are a massive historical data curator. Read the following chunk of academic data extracted from the student's platforms.\n"
        "Your job is to extract all core concepts, important dates, study topics, and knowledge into a highly dense markdown index.\n"
        "Ignore spam, small talk, and unimportant files.\n\n"
        f"SOURCE: {source_name}\n"
        f"DATA:\n{chunk}"
    )
    
    try:
        async with httpx.AsyncClient(timeout=None) as client:
            response = await client.post(
                "http://localhost:11434/api/generate",
                json={
                    "model": "llama3.1:latest",
                    "prompt": prompt,
                    "stream": False
                }
            )
        if response.status_code == 200:
            return response.json().get("response", "").strip()
        else:
            logger.error(f"Error {response.status_code} from Ollama.")
            return None
    except Exception as e:
        logger.error(f"Exception during Ollama call: {e}")
        return None

async def run_indexing():
    if not os.path.exists(ARCHIVE_DIR):
        logger.warning("No offline_archive directory found.")
        return
        
    logger.info("Starting Massive Historical Indexing...")
    
    # Initialize the mega index
    with open(OUTPUT_FILE, "w") as f:
        f.write("# Massive Historical Index\n\nGenerated by Local 8B Model.\n\n")
        
    files = glob.glob(os.path.join(ARCHIVE_DIR, "*.txt"))
    for file_path in files:
        source_name = os.path.basename(file_path)
        with open(file_path, "r", encoding="utf-8") as f:
            text = f.read()
            
        chunks = list(chunk_text(text))
        for i, chunk in enumerate(chunks):
            result = await process_chunk(chunk, i, source_name)
            if result:
                with open(OUTPUT_FILE, "a", encoding="utf-8") as out_f:
                    out_f.write(f"\n\n## Source: {source_name} (Part {i+1})\n\n")
                    out_f.write(result)
                    
    logger.info("Historical Indexing Complete. Output saved to mega_index.md.")

if __name__ == "__main__":
    asyncio.run(run_indexing())
